function [theta_opt, lml] = optimise_lml(X, Y, theta_init, kernel)
%OPTIMISE_LML Optimize the log marginal likelihood w.r.t hyperparameters.
    options = optimoptions('fminunc', ...
        'Algorithm','quasi-newton', ...
        'Display', 'iter', ...
        'PlotFcn', 'optimplotfval', ...
        'MaxFunctionEvaluations', 10000, ...
        'FunctionTolerance', 1e-12, ...
        'OptimalityTolerance', 1e-12, ...
        'StepTolerance', 1e-12);

    f = @(theta) objective(X, Y, theta, kernel);

    [theta_opt, lml] = fminunc(f, theta_init, options);
end

function lml = objective(X, Y, theta, kernel)
    K = build_K(X, Y, theta, kernel);
    lml = -log_marginal_likelihood(K, Y);
end